AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 Auto Scaling Group with ALB in public subnet

Parameters:
  VPCId:
    Type: String
    Description: VPC ID from Terraform
  PublicSubnetId1:
    Type: String
    Description: Public Subnet 1
  PublicSubnetId2:
    Type: String
    Description: Public Subnet 2
  ALBSecurityGroupId:
    Type: String
    Description: Security Group ID for ALB
  EC2SecurityGroupId:
    Type: String
    Description: Security Group ID for EC2
  InstanceAMI:
    Type: AWS::EC2::Image::Id
    Default: ami-0e449927258d45bc4  # Amazon Linux 2 AMI (us-east-1)
  InstanceType:
    Type: String
    Default: t2.micro

Resources:

  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: web-launch-template
      LaunchTemplateData:
        ImageId: !Ref InstanceAMI
        InstanceType: !Ref InstanceType
        SecurityGroupIds:
          - !Ref EC2SecurityGroupId
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            yum update -y
            yum install -y httpd
            systemctl start httpd
            systemctl enable httpd
            echo "<h1>Hello from $(hostname -f)</h1>" > /var/www/html/index.html
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Name
                Value: web-server

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: web-target-group
      Port: 80
      Protocol: HTTP
      VpcId: !Ref VPCId
      TargetType: instance
      HealthCheckPath: /
      Matcher:
        HttpCode: 200

  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: web-alb
      Subnets:
        - !Ref PublicSubnetId1
        - !Ref PublicSubnetId2
      SecurityGroups:
        - !Ref ALBSecurityGroupId
      Scheme: internet-facing
      LoadBalancerAttributes:
        - Key: idle_timeout.timeout_seconds
          Value: "60"

  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup
      LoadBalancerArn: !Ref ALB
      Port: 80
      Protocol: HTTP

  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
        - !Ref PublicSubnetId1
        - !Ref PublicSubnetId2
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      MinSize: '1'
      MaxSize: '3'
      DesiredCapacity: '2'
      TargetGroupARNs:
        - !Ref TargetGroup
      Tags:
        - Key: Name
          Value: web-instance
          PropagateAtLaunch: true

Outputs:
  ALBDNSName:
    Value: !GetAtt ALB.DNSName
    Description: DNS of the load balancer
